# Generated by Django 3.2.15 on 2023-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
    ]
